repository: nterreri/nterreri.github.io
port: 8000
strict_front_matter: true
exclude: ["Gemfile", "Gemfile.lock", "ignore", "yarn.lock", "node_modules", "package.json", ".jshintrc", ".jscsrc"]
include: ["public/*"]
karmdown:
  show_warnings: true
highlighter: rouge

index: /
about: about
privacy: privacy
stylesheet: nt.css
favico: favicon.ico
description: Niccolò is a software developer based in London, has a master's degree in computer science and a couple of years of professional experience. Occasionally writes here about topics related to his work as a developer.
